name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  dist-folder:
    description: 'built files to deploy to surge.sh'
    default: './'
  surge-token:
    description: 'surge login token'
    required: true
  surge-login:
    description: 'surge login email'
    required: true
outputs:
  surge-url:
    description: 'deployed surge site'
runs:
  using: 'node12'
  main: 'index.js'
