name: 'Label controlled Surge deploys'
description: 'Run a build and deploy the result to surge.sh when a PR contains a label'
inputs:
  dist-folder:
    description: 'built files to deploy to surge.sh'
    default: './'
  surge-token:
    description: 'surge login token'
    required: true
  surge-login:
    description: 'surge login email'
    required: true
  label:
    description: 'label to filter PRs'
  build-script:
    description: 'build script to run before deployment'
outputs:
  surge-url:
    description: 'deployed surge site'
runs:
  using: 'node12'
  main: 'index.js'
